### ISSUE TITLE
性能问题 如果一个连接一个线程，而且连接不设置比如1分钟超时，很容易被ddos  

### ISSUE THREAD

**Issue by shopee-jin** [chaseSpace/wukongqueue#12]

**Comment by shopee-jin** [comment]
1连接读写超时
2工作线程池

**Comment by chaseSpace** [comment]
感谢关注！
1. 连接超时确实是一个重要的点，今天会加上
2. 因为通信原理是一个客户端与服务器之间只基于一个tcp长连接通信的，多线程环境下会产生数据混乱，所以这里叫做连接池可能更恰当，谢谢建议，列上TODO。

**Comment by chaseSpace** [comment]
最新的0.0.6版本中已经支持了： 
* 在client和server均支持指定建立连接的timeout参数
* 连接池

再次谢谢关注！
